### PR TITLE
Concatenate JS source files

### PR DESCRIPTION
**Pull request by Zeukkari**
Resolves issue #256.

### CODE REVIEW

**Comment by tituomin** [comment]
The grunt watch task is looking for changed source files. Its configuration contains a reference to a task "newer:coffee:client" which is missing in the new gruntfile. Could you replace it like below:

            'coffee-client':
                files: [
                    'src/*.coffee',
                    'src/views/*.coffee'
                ]
                tasks: ['newer:coffee:home', 'newer:coffee:embed']

**Comment by tituomin** [comment]
The source map references app.src.coffee, which is not catastrophic, but it would be helpful to get the original coffee source file name at a glance.

**Comment by tituomin** [comment]
If you could also concatenate the vendor js, and also maybe css, that would be great!

**Comment by Zeukkari** [comment]
The vendor js files are now concatenated using the requirejs optimizer. Unfortunately the source maps to coffeescript are no longer functioning.

**Pull request closed without merging**
